main:

    log_level: debug
    log_directory: ~/GitHub/pattoo-agents/log
    cache_directory: /mnt/pattoo-ramdisk
    daemon_directory: ~/GitHub/pattoo-agents/daemon
    polling_interval: 10

pattoo-webd:

    api_ip_address: 127.0.0.1
    api_ip_bind_port: 20200
    api_uses_https: False
    web_api_ip_address: 127.0.0.1
    web_api_ip_bind_port: 20202
    web_api_uses_https: False

pattoo-api-agentd:

    api_ip_address: 127.0.0.1
    api_ip_bind_port: 20201
    api_uses_https: False

pattoo-apid:

    api_ip_address: 127.0.0.1
    api_ip_bind_port: 20202
    api_uses_https: False

db:
  db_hostname: localhost
  db_name: pattoo
  db_password: rWPjym8au5cfNy9r
  db_username: pattoo
  db_pool_size: 10
  db_max_overflow: 200

pattoo-agent-os-spoked:

    listen_address: 127.0.0.1
    ip_bind_port: 5000

pattoo-agent-os-hubd:

    ip_devices:
      - ip_address: 127.0.0.1
        ip_bind_port: 5000

pattoo-agent-snmpd:

  polling_groups:
    - group_name: TEST
      ip_devices:
        - localhost
      oids:
        - address: .1.3.6.1.2.1.2.2.1.10
        - address: .1.3.6.1.2.1.2.2.1.16

  auth_groups:
    - group_name: TEST
      snmp_authpassword: null
      snmp_authprotocol: null
      snmp_community: constipayted
      snmp_port: 161
      snmp_privpassword: null
      snmp_privprotocol: null
      snmp_secname: null
      snmp_version: 2
      ip_devices:
        - localhost

pattoo-agent-modbustcpd:

  polling_groups:
    - group_name: TEST
      ip_devices:
        - test.modbus.tcp.device.net
      input_registers:
        - 387
        - 388
      holding_registers:
        - 123
        - 456
